apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: events-external
  name: events-external
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-external
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: events-external
    spec:
      containers:
      - image: jipara/external:v1
        name: events-external
        ports:
        - containerPort: 8080
        env:
        - name: SERVER
          value: "http://events-internal:8082"
